services:
  - type: web
    name: localde-calisiyordu-api
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: localde-calisiyordu-db
          property: connectionString

databases:
  - name: localde-calisiyordu-db
    plan: basic-256mb
    databaseName: localde_calisiyordu
    user: localde_calisiyordu
